### ISSUE TITLE
"brew list" does not show anything

### ISSUE THREAD

**Issue by outcoldman** [fniephaus/alfred-homebrew#4]
When I do "brew list" I see only "Search ... for brew list", but no brew packages. 
This is the output of `python brew.py "list"`

```
09:48:22 workflow.py:2053 DEBUG    Update check not due
09:48:22 workflow.py:1544 DEBUG    Loading cached data from : /Users/outcoldman/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.homebrew/__workflow_update_status.cpickle
09:48:22 workflow.py:1544 DEBUG    Loading cached data from : /Users/outcoldman/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.homebrew/brew_not_installed.cpickle
09:48:22 workflow.py:1544 DEBUG    Loading cached data from : /Users/outcoldman/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.homebrew/brew_installed_formulas.cpickle
<?xml version="1.0" encoding="utf-8"?>
<items><item valid="yes"><title>ant 1.9.3 1.9.4</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/ant.rb &amp;&amp; exit</arg></item><item valid="yes"><title>autoconf 2.69</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/autoconf.rb &amp;&amp; exit</arg></item><item valid="yes"><title>automake 1.14.1</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/automake.rb &amp;&amp; exit</arg></item><item valid="yes"><title>boost 1.56.0</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/boost.rb &amp;&amp; exit</arg></item><item valid="yes"><title>class-dump 3.5</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/class-dump.rb &amp;&amp; exit</arg></item><item valid="yes"><title>cmake 2.8.12.2 3.0.0 3.0.1 3.0.2</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/cmake.rb &amp;&amp; exit</arg></item><item valid="yes"><title>docker 1.3.1 1.3.2</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/docker.rb &amp;&amp; exit</arg></item><item valid="yes"><title>gdbm 1.11</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/gdbm.rb &amp;&amp; exit</arg></item><item valid="yes"><title>git 1.9.1 1.9.2 2.0.0 2.0.1 2.1.0 2.1.2 2.1.3</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/git.rb &amp;&amp; exit</arg></item><item valid="yes"><title>go 1.3.3</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/go.rb &amp;&amp; exit</arg></item><item valid="yes"><title>htop-osx 0.8.2.2</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/htop-osx.rb &amp;&amp; exit</arg></item><item valid="yes"><title>httpie 0.8.0</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/httpie.rb &amp;&amp; exit</arg></item><item valid="yes"><title>jmeter 2.11 2.12</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/jmeter.rb &amp;&amp; exit</arg></item><item valid="yes"><title>libevent 2.0.21 2.0.21_1</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/libevent.rb &amp;&amp; exit</arg></item><item valid="yes"><title>libtool 2.4.2</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/libtool.rb &amp;&amp; exit</arg></item><item valid="yes"><title>mongodb 2.6.0_1 2.6.1 2.6.2 2.6.3 2.6.4_1 2.6.5</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/mongodb.rb &amp;&amp; exit</arg></item><item valid="yes"><title>ngrok 1.6 1.7</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/ngrok.rb &amp;&amp; exit</arg></item><item valid="yes"><title>ninja 1.5.1</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/ninja.rb &amp;&amp; exit</arg></item><item valid="yes"><title>node 0.10.26 0.10.28 0.10.29 0.10.31 0.10.33 0.10.33_1</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/node.rb &amp;&amp; exit</arg></item><item valid="yes"><title>openssl 1.0.1g 1.0.1h 1.0.1i 1.0.1j</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/openssl.rb &amp;&amp; exit</arg></item><item valid="yes"><title>p7zip 9.20.1</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/p7zip.rb &amp;&amp; exit</arg></item><item valid="yes"><title>perforce 2014.1.821990</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/perforce.rb &amp;&amp; exit</arg></item><item valid="yes"><title>python 2.7.6_1 2.7.7_1 2.7.7_2 2.7.8 2.7.8_1 2.7.8_2</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/python.rb &amp;&amp; exit</arg></item><item valid="yes"><title>readline 6.2.4 6.3.3 6.3.6 6.3.8</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/readline.rb &amp;&amp; exit</arg></item><item valid="yes"><title>sqlite 3.8.4.3 3.8.5 3.8.6 3.8.7 3.8.7.1</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/sqlite.rb &amp;&amp; exit</arg></item><item valid="yes"><title>ssh-copy-id 6.6p1</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/ssh-copy-id.rb &amp;&amp; exit</arg></item><item valid="yes"><title>tig 1.2.1 2.0.1 2.0.2 2.0.3</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/tig.rb &amp;&amp; exit</arg></item><item valid="yes"><title>tmux 1.9a</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/tmux.rb &amp;&amp; exit</arg></item><item valid="yes"><title>tree 1.7.0</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/tree.rb &amp;&amp; exit</arg></item><item valid="yes"><title>unrar 5.1.4 5.1.5 5.1.6 5.1.7 5.2.1 5.2.2</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/unrar.rb &amp;&amp; exit</arg></item><item valid="yes"><title>wget 1.15_1 1.15_2 1.16</title><subtitle>Open on GitHub</subtitle><arg>open https://github.com/Homebrew/homebrew/tree/master/Library/Formula/wget.rb &amp;&amp; exit</arg></item></items>09:48:22 background.py:180 DEBUG    Command arguments cached to `/Users/outcoldman/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.homebrew/brew_refresh.argcache`
09:48:22 background.py:184 DEBUG    Calling [u'/usr/bin/python', '/Users/outcoldman/dev/github/alfred-homebrew/src/workflow/background.pyc', 'brew_refresh'] ...
09:48:22 workflow.py:1907 DEBUG    Workflow finished in 0.001 seconds.
09:48:22 workflow.py:1907 DEBUG    Workflow finished in 0.002 seconds.
09:48:22 background.py:189 DEBUG    Executing task `brew_refresh` in background...
```

And this is my output of `brew list`

```
ant		class-dump	go		libtool		openssl		sqlite		unrar
autoconf	cmake		htop-osx	mongodb		p7zip		ssh-copy-id	wget
automake	docker		httpie		ngrok		perforce	tig
boost		gdbm		jmeter		ninja		python		tmux
brew-cask	git		libevent	node		readline	tree
```

**Comment by scottelundgren** [comment]
I'm having a similar issue:
```
cd ~/Library/Application\ Support/Alfred\ 2/Alfred.alfredpreferences/workflows/user.workflow.2514D317-E0DD-47C1-B3F0-C12EEB4D26F6/
```

```
python brew.py "list"
10:40:59 workflow.py:2181 DEBUG    update_data : None
10:40:59 workflow.py:1610 DEBUG    Loading cached data from : /Users/scottlundgren/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.homebrew/brew_not_installed.cpickle
10:40:59 workflow.py:1610 DEBUG    Loading cached data from : /Users/scottlundgren/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.fniephaus.homebrew/brew_installed_formulas.cpickle
Traceback (most recent call last):
  File "brew.py", line 124, in <module>
    icon=get_icon("package")
  File "brew.py", line 62, in get_icon
    name = '%s-dark' % name if is_dark() else name
  File "brew.py", line 67, in is_dark
    return min([int(x) for x in WF.alfred_env['theme_background'][5:-6].split(',')]) < 128
TypeError: 'NoneType' object has no attribute '__getitem__'
```

```
brew list
autoconf	bash-completion	brew-cask	dnsmasq		hub		nodenv		openssl		pkg-config	rbenv		ruby-build
```

**Comment by fniephaus** [comment]
If you call brew.py directly from your Terminal, it will fail because it does not run in an Alfred environment (which contains `theme_background`). But I should make that code better at some point.

@scottelundgren can you use Alfred's debugger and post the output?

**Comment by fniephaus** [comment]
@scottelundgren @outcoldman are you guys still having this problem?

**Comment by fniephaus** [comment]
Please try [v4.0](https://github.com/fniephaus/alfred-homebrew/releases/tag/v4.0) and reopen this if the problem persists.
